FROM php:8.2-apache

RUN apt-get update && apt-get install -y \
libpq-dev \
git \
zip \
unzip \
&& docker-php-ext-install pdo pdo_pgsql

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html

COPY . .

RUN composer install --no-dev --optimize-autoloader

RUN a2enmod rewrite

EXPOSE 80